import { getOrCreateEmbedConfig } from "@/lib/embed";
import { logAuditEntry } from "@/lib/audit";
import { getAppUrl } from "@/lib/env";

/**
 * Layer 24-4: generates one complete, pre-configured WooCommerce plugin
 * file per merchant — merchant id and publishable key baked in, so the
 * merchant never types a key (the single most error-prone step in every
 * other integration flow). Carries no secret: both baked-in values are
 * exactly the origin-bound, non-authenticating publishable key Layer 10
 * already established, never the agent secret key.
 *
 * Deterministic string generation only — same merchant, same output,
 * byte for byte, proven in woocommerce-plugin.test.ts. No LLM anywhere
 * in this path.
 *
 * The plugin does three things through WooCommerce's own hook system,
 * never by editing a theme file:
 *  1. Registers a rewrite rule + template_redirect that serves the
 *     merchant's real, live discovery manifest at
 *     /.well-known/agent-commerce.json — proxied from this app's own
 *     /store/[merchantId]/manifest.json rather than duplicated in PHP,
 *     so the WordPress copy can never drift from the real one.
 *  2. Injects the widget script tag via wp_footer.
 *  3. Adds schema.org/Product JSON-LD to each WooCommerce product page
 *     via woocommerce_single_product_summary — real WooCommerce product
 *     data (price, SKU, stock), read at render time, never fabricated.
 *
 * Idempotent on re-activation (register_activation_hook only sets one
 * option flag, safe to run twice) and removes cleanly on deactivation
 * (register_deactivation_hook flushes the rewrite rule it added).
 */

export interface WooCommercePluginOptions {
  merchantId: string;
  merchantName: string;
  publishableKey: string;
  appOrigin: string;
}

function phpStringLiteral(value: string): string {
  // Single-quoted PHP string: only \ and ' need escaping. Every value
  // baked in here (a UUID, a "pk_..." key, a merchant name, an https URL)
  // is either machine-generated or a merchant's own account name, but
  // this escaping is applied unconditionally rather than assumed safe.
  return `'${value.replace(/\\/g, "\\\\").replace(/'/g, "\\'")}'`;
}

export function generateWooCommercePlugin(opts: WooCommercePluginOptions): string {
  const merchantId = phpStringLiteral(opts.merchantId);
  const merchantName = phpStringLiteral(opts.merchantName);
  const publishableKey = phpStringLiteral(opts.publishableKey);
  const appOrigin = phpStringLiteral(opts.appOrigin.replace(/\/$/, ""));

  return `<?php
/**
 * Plugin Name: Thirdman Agent Commerce
 * Description: Generated by your Thirdman dashboard (/dashboard/integrations) for this store only. Serves the agent discovery document, injects the buyer widget, and adds Product structured data to your WooCommerce product pages. Safe to deactivate at any time — deactivating removes everything it added.
 * Version: 1.0.0
 * Requires Plugins: woocommerce
 *
 * Generated by thirdman for merchant ${opts.merchantName.replace(/\*/g, "")} (${opts.merchantId}).
 * Carries no secret: the value below is a publishable embed key, safe to
 * appear in public HTML — see /dashboard/embed. Re-download from your
 * dashboard if this merchant's key is ever rotated.
 */

if (!defined('ABSPATH')) {
    exit; // Direct access is not allowed.
}

define('THIRDMAN_MERCHANT_ID', ${merchantId});
define('THIRDMAN_MERCHANT_NAME', ${merchantName});
define('THIRDMAN_PUBLISHABLE_KEY', ${publishableKey});
define('THIRDMAN_APP_ORIGIN', ${appOrigin});

/**
 * 1. Discovery document: /.well-known/agent-commerce.json on THIS store,
 * proxied from the real, live manifest this merchant's Thirdman account
 * already serves — never a static copy that could go stale.
 */
add_action('init', function () {
    add_rewrite_rule('^\\.well-known/agent-commerce\\.json$', 'index.php?thirdman_manifest=1', 'top');
});

add_filter('query_vars', function ($vars) {
    $vars[] = 'thirdman_manifest';
    return $vars;
});

add_action('template_redirect', function () {
    if (!get_query_var('thirdman_manifest')) {
        return;
    }

    $upstream = THIRDMAN_APP_ORIGIN . '/store/' . rawurlencode(THIRDMAN_MERCHANT_ID) . '/manifest.json';
    $response = wp_remote_get($upstream, array('timeout' => 5));

    header('Content-Type: application/json');
    if (is_wp_error($response) || wp_remote_retrieve_response_code($response) !== 200) {
        status_header(502);
        echo wp_json_encode(array(
            'error' => 'Could not reach the live discovery document for this merchant.',
        ));
        exit;
    }

    echo wp_remote_retrieve_body($response);
    exit;
});

/**
 * 2. The buyer widget, appended once via the theme's own wp_footer hook
 * — nothing in this plugin edits a theme file.
 */
add_action('wp_footer', function () {
    printf(
        '<script async src="%s/api/embed/v1.js" data-embed-key="%s"></script>',
        esc_url(THIRDMAN_APP_ORIGIN),
        esc_attr(THIRDMAN_PUBLISHABLE_KEY)
    );
});

/**
 * 3. schema.org/Product structured data on each product page, read from
 * WooCommerce's own product object at render time — real price, real
 * SKU, real stock status, never a placeholder value.
 */
add_action('woocommerce_single_product_summary', function () {
    global $product;
    if (!$product || !is_a($product, 'WC_Product')) {
        return;
    }

    $data = array(
        '@context' => 'https://schema.org/',
        '@type' => 'Product',
        'name' => $product->get_name(),
        'sku' => $product->get_sku(),
        'description' => wp_strip_all_tags($product->get_short_description()),
        'offers' => array(
            '@type' => 'Offer',
            'priceCurrency' => get_woocommerce_currency(),
            'price' => $product->get_price(),
            'availability' => $product->is_in_stock()
                ? 'https://schema.org/InStock'
                : 'https://schema.org/OutOfStock',
        ),
    );

    echo '<script type="application/ld+json">' . wp_json_encode($data) . '</script>';
}, 25);

register_activation_hook(__FILE__, function () {
    // Flushing rewrite rules is safe to run on every activation, including
    // a re-activation after deactivation — WordPress dedupes by rule key.
    flush_rewrite_rules();
});

register_deactivation_hook(__FILE__, function () {
    flush_rewrite_rules();
});
`;
}

/**
 * Reads the merchant's real embed config (creating one if this is their
 * first integration surface) and generates their plugin file. Every call
 * is audited — a merchant downloading an integration artifact is a real,
 * traceable event even though it moves no money.
 */
export async function generateWooCommercePluginForMerchant(merchantId: string, merchantName: string): Promise<{ filename: string; content: string }> {
  const embedConfig = await getOrCreateEmbedConfig(merchantId);
  const appOrigin = getAppUrl();

  const content = generateWooCommercePlugin({
    merchantId,
    merchantName,
    publishableKey: embedConfig.publishableKey,
    appOrigin,
  });

  await logAuditEntry({
    merchantId,
    actor: "merchant",
    event: "woocommerce_plugin_generated",
    decision: "n/a",
    reason: "Merchant generated the WooCommerce integration plugin from the dashboard.",
  });

  return { filename: "thirdman-agent-commerce.php", content };
}
