export const TOOL_VERSION = "0.1.0";
export const HEADER_TEXT = `Generated by thirdman v${TOOL_VERSION} (npx thirdman init) — see /dashboard/cli. Safe to edit; re-running init will show you a diff before overwriting.`;
/** Every generated JS/TS file carries this so a merchant reading their own repo in six months knows what wrote it — L20-5. */
export function generatedFileHeaderJs() {
    return `// ${HEADER_TEXT}\n`;
}
export function generatedFileHeaderHtml() {
    return `<!-- ${HEADER_TEXT} -->\n`;
}
/** .well-known/agent-commerce.json must stay valid, headerless JSON for any consumer to parse — the header goes in a sibling "_generatedBy" field instead of a comment. */
export function generatedByField() {
    return { _generatedBy: HEADER_TEXT };
}
//# sourceMappingURL=headers.js.map